CLASS zbp_kkr_i_position DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF zkkr_i_position.
  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zbp_kkr_i_position IMPLEMENTATION.
ENDCLASS.