name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Check repository structure
      run: |
        test -d src || (echo "src directory missing" && exit 1)
        test -d tests || (echo "tests directory missing" && exit 1)
        test -f README.md || (echo "README.md missing" && exit 1)
        test -f LICENSE || (echo "LICENSE missing" && exit 1)

    - name: Validate documentation
      run: |
        if ! grep -q "^## Test Class Structure" rap-rules.md; then
          echo "Test class documentation missing"
          exit 1
        fi

    - name: Validate markdown files
      run: |
        find . -type f -name "*.md" -print0 | while IFS= read -r -d '' file; do
          if ! grep -q "^#" "$file"; then
            echo "Warning: Markdown file $file missing header"
          fi
        done