name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Check file structure
      run: |
        test -d src || (echo "src directory missing" && exit 1)
        test -d tests || (echo "tests directory missing" && exit 1)
        test -f README.md || (echo "README.md missing" && exit 1)
        test -f LICENSE || (echo "LICENSE missing" && exit 1)
        test -f rap-rules.md || (echo "rap-rules.md missing" && exit 1)

    - name: Validate documentation
      run: |
        if ! grep -q "## Test Class Structure" rap-rules.md; then
          echo "Test class documentation missing"
          exit 1
        fi

    - name: Check file naming conventions
      run: |
        # Check for proper SAP RAP naming conventions
        find . -type f -name "*.abap" | while read file; do
          if ! [[ $(basename "$file") =~ ^[zy][_a-z0-9]+\.(clas|intf|prog|ddls)\.abap$ ]]; then
            echo "Invalid ABAP file name: $file"
            exit 1
          fi
        done

    - name: Validate markdown files
      run: |
        find . -type f -name "*.md" -exec markdown-lint {} \; || true